### ISSUE TITLE
Is there any documentation for installation? (*basic usage)

### ISSUE THREAD

**Issue by ardzz** [ulbrich-media/clubcms#2]

**Comment by ulbrich-media** [comment]
Not yet, I will add documentation once I'm done with all the basic features and ready to release version 1.

There is a composer based [distribution package](https://github.com/ulbrich-media/clubcms-distribution) for a quick installation of TYPO3. 
Once installed this extension gives you a handful of content elements, a page template and some additional options in page properties and site configuration.
